@Library('workflowlib-sandbox@v4.8')
import com.lbg.workflow.sandbox.*

withEnv(["BRANCH_NAME=master"]){
    veracodeDownload('ob-aisp-account-request-data-api', 'pipelines/conf/job-configuration.json')
}
