--------------------  DDL for Table ACCT_REQUEST----------------------------
  
ALTER TABLE "ACCOUNTREQUEST"."ACCT_REQUEST" 
ADD "ENT_ACCESS_CODE" VARCHAR2(255 BYTE); 


--ALTER TABLE "ACCOUNTREQUEST"."ACCT_REQUEST"
--DROP COLUMN "ENT_ACCESS_CODE";
