spring:
  profiles:
    default: development
    active: development
  datasource:
    #url: jdbc:oracle:thin:@10.112.159.86:40000/xe
    #username: ACCOUNTREQUEST
    #password: password
    #driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    user: sa
    password:
  jpa:
    database: H2
    hibernate.ddl-auto: update
  #h2.console.enabled: true
    initialSize: 3 
    maxActive: 5
    maxIdle: 1
    minIdle: 1
    removeAbandoned: true
    removeAbandonedTimeout: 120
    timeBetweenEvictionRunsMillis: 1000
    minEvictableIdleTimeMillis: 1000   
    tomcat:
      max-active: 1 
      min-idle: 1
      initialSize: 1 
  h2.console.enabled: true


---
entitlementRevokeUrl: http://j2-ob-cnf-entitlement-api-master.lbg.eu-gb.mybluemix.net/entitlement-service/v1.0/entitlements/status/revoke

spring:
  profiles: development

# context Path
server:
    port: 8080

---

spring:
  profiles: test

# context Path
server:
    port: 8080


---

spring:
  profiles: production

# context Path
server:
    port: 8080

       
---
# common properties for yaml

entitlementRevokeUrl: ${entitlementRevokeUrl}

# headers
header:
      xlbginternaluserid: x-lbg-internal-user-id
      xlbginternaluserrole: x-lbg-internal-user-role
      xlbgtxncorrelationid: x-lbg-txn-correlation-id

# context Path
server:
      contextPath: /account-request-data/v1.1

# API Documentation
documentation:
       title: Spring REST with Swagger
       description: Spring REST with Swagger

hystrix:
  command:
    database:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 800000
          strategy: THREAD
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50
    entitlementService:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000
            interruptOnTimeout: true
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50

