spring:
  profiles:
    default: development
    active: development
  datasource:
    jndi-name: java:comp/DefaultDataSource
---

spring:
  profiles: development

# context Path
server:
    port: 8080

---

spring:
  profiles: test

# context Path
server:
    port: 8080


---

spring:
  profiles: production

# context Path
server:
    port: 8080


---
# common properties for yaml

# headers
header:
      xlbginternaluserid: x-lbg-internal-user-id
      xlbginternaluserrole: x-lbg-internal-user-role
      xlbgtxncorrelationid: x-lbg-txn-correlation-id

# context Path
server:
      contextPath: /account-request-data

# API Documentation
documentation:
       title: Spring REST with Swagger
       description: Spring REST with Swagger

hystrix:
  command:
    database:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${hystrixThreadTimeoutInMillis}
            interruptOnTimeout: true
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        sleepWindowInMilliseconds: ${circuitSleepWindowMillis}
        requestVolumeThreshold: ${requestVolumeThreshold}
        errorThresholdPercentage: ${errorThresholdPercentage}
    entitlementService:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${hystrixThreadTimeoutInMillis}
            interruptOnTimeout: true
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        sleepWindowInMilliseconds: ${circuitSleepWindowMillis}
        requestVolumeThreshold: ${requestVolumeThreshold}
        errorThresholdPercentage: ${errorThresholdPercentage}
